apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: payment-postgres
data:
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-postgres
  template:
    metadata:
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres-srv
spec:
  selector:
    app: payment-postgres
  ports:
    - port: 5432
      targetPort: 5432
